{% raw %}---
- name: add rabbitmq signing key
  sudo: True
  apt_key: >
    url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    state=present
  tags:
    - rabbitmq

- name: add rabbitmq apt repo
  apt_repository: >
    repo='deb http://www.rabbitmq.com/debian/ testing main'
    update_cache=yes
    state=present
  tags:
    - rabbitmq

- name: install rabbitmq-server packages
  apt: >
    pkg=rabbitmq-server
    update_cache=yes
    cache_valid_time={{six_hours}}
    state=installed
  tags:
    - rabbitmq

- name: ensure rabbitmq is stopped
  service: >
    name=rabbitmq-server
    state=stopped
  tags:
    - rabbitmq

- name: enable rabbitmq plugins
  rabbitmq_plugin: >
    names=rabbitmq_management,rabbitmq_tracing
    state=enabled
  notify:
  - restart rabbitmq
  tags:
    - rabbitmq

- name: copy rabbitmq.config file
  copy: >
    src=rabbitmq.config
    dest=/etc/rabbitmq/rabbitmq.config
  tags:
    - rabbitmq

- name: ensure rabbitmq is started
  service: >
    name=rabbitmq-server
    state=started
  tags:
    - rabbitmq

- name: "ensure vhost /{{project_name}} is present"
  rabbitmq_vhost: >
    name=/{{project_name}}
    node={{rabbit_node}}
    state=present
  tags:
    - rabbitmq

- name: add admin user
  rabbitmq_user: >
    user=admin
    password={{rabbitmq_admin_password}}
    tags=administrator
    vhost=/
    configure_priv=.*
    write_priv=.*
    read_priv=.*
    node={{rabbit_node}}
    state=present
  tags:
    - rabbitmq

- name: "add {{rabbitmq_user}} user"
  rabbitmq_user: >
    user={{rabbitmq_user}}
    password={{rabbitmq_password}}
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    vhost=/{{project_name}}
    tags={{project_name}}
    node={{rabbit_node}}
    state=present
  tags:
    - rabbitmq

- name: remove default guest user
  rabbitmq_user: >
    user=guest
    node={{rabbit_node}}
    state=absent
  tags:
    - rabbitmq
{% endraw %}
