{% raw %}---
- name: add nginx ppa
  apt_repository: repo=ppa:nginx/stable state=present update_cache=yes
  tags:
    - nginx

- name: install nginx package
  apt: pkg=nginx state=latest update_cache=yes cache_valid_time={{six_hours}}
  sudo: True
  tags:
    - nginx

- name: remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx
  tags:
    - nginx

- name: write nginx.conf
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf # validate="nginx -t -c %s"
  notify:
    - restart nginx
  tags:
    - nginx

- name: add vhost config to sites-available
  template: src=nginx_vhost.j2 dest=/etc/nginx/sites-available/{{project_name}}.conf
  tags:
    - nginx

- name: symlink nginx site conf to sites-enabled
  file: src=/etc/nginx/sites-available/{{project_name}}.conf dest=/etc/nginx/sites-enabled/{{project_name}}.conf state=link
  notify:
    - restart nginx
  tags:
    - nginx{% endraw %}
