---
fqdn: {{cookiecutter.domain_name}}
root_user: root
{% raw %}
# postgres
postgres_user_name: "pg_{{ project_name }}"
postgres_db_name: "db_{{ project_name }}"
postgres_password: change_me

# rabbitmq
rabbitmq_user: django
rabbitmq_password: changeme
rabbit_node: rabbit@localhost

reqs_file: production.txt

is_production: True

env_vars:
  DJANGO_SECRET_KEY: YOU_HAVE_TO_CHANGE_ME!!!
  DJANGO_SETTINGS_MODULE: config.settings
  DJANGO_CONFIGURATION: Production
  DATABASE_URL: "postgres://{{ postgres_user_name }}:{{ postgres_password }}@localhost:5432/{{ postgres_db_name }}"
  RABBITMQ_URL: "amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@localhost:5672//{{ project_name }}"
{% endraw %}
